### ISSUE TITLE
amplify initするとspawn xdg-open ENOENTのエラーが発生するようになった

### ISSUE THREAD

**Issue by matyuda** [shigeru-oda/zenn#6]
$ amplify init
Note: It is recommended to run this command from the root of your app directory
? Enter a name for the environment xxxxx
? Choose your default editor: Visual Studio Code
Using default provider  awscloudformation
? Select the authentication method you want to use: AWS profile
AWS access credentials can not be found.
? Setup new user Yes
Follow these steps to set up access to your AWS account:

Sign in to your AWS administrator account:
https://console.aws.amazon.com/
Press Enter to continue
2022-04-10T01:08:24.293Z - error: uncaughtException: spawn xdg-open ENOENT date=Sun Apr 10 2022 01:08:24 GMT+0000 (Coordinated Universal Time), pid=15181, uid=1000, gid=1000, cwd=/home/ec2-user/environment/work/amplify-homes, execPath=/home/ec2-user/.amplify/bin/amplify, version=v14.18.1, argv=[/home/ec2-user/.amplify/bin/amplify, /snapshot/node_modules/@aws-amplify/cli-internal/bin/amplify, init], rss=351547392, heapTotal=269807616, heapUsed=224473960, external=10079462, arrayBuffers=8338245, loadavg=[0.47, 0.35, 0.21], uptime=759.82, trace=[column=19, file=internal/child_process.js, function=Process.ChildProcess._handle.onexit, line=274, method=onexit, native=false, column=16, file=internal/child_process.js, function=onErrorNT, line=469, method=null, native=false, column=21, file=internal/process/task_queues.js, function=processTicksAndRejections, line=82, method=null, native=false], stack=[Error: spawn xdg-open ENOENT,     at Process.ChildProcess._handle.onexit (internal/child_process.js:274:19),     at onErrorNT (internal/child_process.js:469:16),     at processTicksAndRejections (internal/process/task_queues.js:82:21)]

**Comment by matyuda** [comment]
nvm use 16.14.0 とすると以下の警告は出るもののamplify initは成功する。

> Select the authentication method you want to use: (Use arrow keys)
> ❯ AWS profile 
 > AWS access keys (node:23164) [DEP0128] DeprecationWarning: Invalid 'main' field in '/home/ec2-user/.nvm/versions/node/v16.14.0/lib/node_modules/@aws-amplify

**Comment by matyuda** [comment]
xdg-open がインストールされていないことが原因。
sudo yum install xdg-utils
を実行すれば解消する。

Cloud9のAmazon Linux2 AMIイメージが4/8に ami-076a9fce461fc493f ( Cloud9AmazonLinux2-2022-04-08T14-17 )に変更されたことが原因？
